name: Test and Build Yocto Image

on:
  push:
    branches: [ "master", "develop" ]
    paths-ignore: [ '**.md', '**.pdf', '**.yml' ]
  pull_request:
    branches: [ "master", "develop" ]
    paths-ignore: [ '**.md', '**.pdf', '**.yml' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  check-submodule:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Assign variable based on branch name
        run: |
          target_branch=${{ github.base_ref }}
          # Set another value if the variable is empty
          target_branch="${target_branch:-${{ github.ref_name }}}"
          
          echo "The target branch is: $target_branch"

          # Set the value of the environment variable with the same name as the variable
          echo "target_branch=$target_branch" >> $GITHUB_ENV
          
      - name: 'Check meta-mistysom Submodule Branch'
        uses: jtmullen/submodule-branch-check-action@v1.2.2
        with:
          path: Build/meta-mistysom
          branch: ${{ env.target_branch }}
          require_head: true

      - name: 'Check meta-econsys Submodule Branch'
        uses: jtmullen/submodule-branch-check-action@v1.2.2
        with:
          path: Build/meta-econsys
          branch: ${{ env.target_branch }}
          require_head: true

  build-yocto:
    runs-on: DC02
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Build the Docker image
      run: cd Build && ./build.sh; 
    
    - name: Run the Docker container and build output files
      run: |
        cd Build
        ./run.sh -c /home/github/rzg2l-cache
        cp output/images/smarc-rzv2l/*.wic.bz2 /home/github
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output-image
        path: Build/output/images/smarc-rzg2l/mistysom-image-smarc-rzg2l.wic.bz2
